version: "3.3"
services:
    memcached:
        image: 'memcached:alpine'
        networks:
            - app-network

    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '27000:8025'
        networks:
            - app-network

    # PHP service
    app:
        build: .
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./var/logs/php:/var/log/
        networks:
            - app-network

    # MySQL database service
    db:
        #command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./var/mysql:/var/lib/mysql
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./var/logs/nginx:/var/log/nginx/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
